version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - tchssk
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: goa.design/goa/v3
    reviewers:
      - tchssk
